# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='is_doctor',
        ),
    ]
