# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20190120_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery', models.BooleanField(default=False, verbose_name='Any surgery within the last five years')),
                ('allergies', models.BooleanField(default=False, verbose_name='Allergies(including massage oils)')),
                ('epilepsy', models.BooleanField(default=False)),
                ('pacemaker', models.BooleanField(default=False, verbose_name='Any metal pins or plates as a result of surgery')),
                ('circulatory_problems', models.BooleanField(default=False, verbose_name='Any circulatory problems, Thrombosis etc)')),
                ('illness', models.BooleanField(default=False, verbose_name='Major Illness/ injury')),
                ('liver_kidney_ailments', models.BooleanField(default=False, verbose_name='Liver/Kidney ailments')),
                ('medication', models.BooleanField(default=False, verbose_name='Are you currently taking any form ofmedication(including Homeopathic remedies')),
                ('back_pains', models.BooleanField(default=False, verbose_name='Back pains')),
                ('nervous_disorders', models.BooleanField(default=False, verbose_name='Nervous disorders')),
                ('blood_born_diseases', models.BooleanField(default=False, verbose_name='Blood born diseases (Hep B, AIDS, HIV)')),
                ('reduced_reflexes', models.BooleanField(default=False, verbose_name='Reduced reflexes(if known)')),
                ('broken_capillaries', models.BooleanField(default=False, verbose_name='Broken capillaries')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
